// Interface text in English. Every key must also exist in pt.ts (TypeScript checks it).
export const en = {
  "a11y.breadcrumb": "Breadcrumb",
  "a11y.skip": "Skip to content",
  "about.bio":
    "I'm based in Lisbon and have been building for the web since 2023, mostly with React, Next.js and TypeScript.\n\nBefore that I was an architect, and I wrote my master's thesis on architecture and video games. Games stuck with me: several of my own projects are game companions, like Voydex, a Pokémon companion I'm building now. The rest are mostly small trackers for things I care about, from concerts to finances.",
  "about.facts.based": "Based in",
  "about.facts.current": "Currently",
  "about.facts.degree": "Degree",
  "about.facts.frontendSince": "Frontend since",
  "about.intro":
    "A frontend developer with a background in architecture and an interest in UX and UI.",
  "about.method.access.body":
    "I use semantic HTML, keyboard support and good contrast, and test on different screen sizes.",
  "about.method.access.title": "Accessibility",
  "about.method.design.body":
    "I pay attention to hierarchy, spacing and states, so screens are easy to read.",
  "about.method.design.title": "Design",
  "about.method.intro": "Four principles behind everything I build.",
  "about.method.longevity.body":
    "I write typed, readable code and tidy up as I go, so it stays easy to change.",
  "about.method.longevity.title": "Longevity",
  "about.method.structure.body":
    "I plan components and layouts before building, so new features are easier to add.",
  "about.method.structure.title": "Structure",
  "about.method.title": "How I work.",
  "about.story.practice.title": "Architect",
  "about.story.school.title": "Architecture school",
  "about.story.software.body":
    "Full-stack roles at Subvisual and Talent Protocol, then frontend at Aquasis, with client and personal projects along the way.",
  "about.story.software.title": "Frontend",
  "about.story.title": "How I got into frontend.",
  "about.story.transition.title": "The switch",
  "about.title": "Hi, I'm Tiago.",
  "about.toolbox.title": "What I work with.",
  "common.all": "All",
  "common.backToTop": "Back to top",
  "common.entries": "entries",
  "common.entry": "entry",
  "common.fullTimeline": "Full timeline",
  "common.next": "Next",
  "common.portraitAlt": "Portrait of Tiago Gil outdoors at sunset, looking to the side.",
  "common.present": "Present",
  "common.previous": "Previous",
  "contact.body":
    "I'm available for freelance projects: websites, web apps and interfaces. The quickest way to reach me is email.",
  "contact.copied": "Copied",
  "contact.copy": "Copy email",
  "contact.cv": "Download CV",
  "contact.title": "Let's talk.",
  "duration.month": "mo",
  "duration.months": "mos",
  "duration.year": "yr",
  "duration.years": "yrs",
  "footer.contact": "Contact",
  "footer.index": "Index",
  "footer.note": "Frontend developer and former architect, based in Lisbon.",
  "footer.updated": "Last updated",
  "home.experience.title": "Where I've worked.",
  "home.hero.ctaWork": "See selected work",
  "home.hero.lead":
    "I work mainly with React, Next.js and TypeScript. My background in architecture makes me care a lot about structure and design. Currently at Aquasis, in Lisbon, and available for freelance.",
  "home.hero.line1": "Frontend developer",
  "home.hero.line2": "& architect.",
  "home.work.all": "All projects",
  "home.work.title": "A few things I've designed and built.",
  "language.label": "Language",
  "lightbox.counter": "{n} of {total}",
  "lightbox.label": "Images of {title}",
  "lightbox.next": "Next image",
  "lightbox.previous": "Previous image",
  "nav.about": "About",
  "nav.close": "Close",
  "nav.contact": "Contact",
  "nav.home": "Home",
  "nav.homeLabel": "Tiago Gil, home",
  "nav.label": "Main",
  "nav.menu": "Menu",
  "nav.projects": "Projects",
  "nav.timeline": "Timeline",
  "notFound.body":
    "It may have moved, or the address may be wrong. The home page is a good place to start again.",
  "notFound.home": "Back to home",
  "notFound.label": "Not found",
  "notFound.title": "This page doesn't exist.",
  "project.brief": "Brief",
  "project.collection": "In this collection",
  "project.context": "Context",
  "project.enlarge": "Enlarge",
  "project.figures": "Figures",
  "project.imageNumbered": "Screenshot {n} of {total} of {title}",
  "project.personal": "Personal project",
  "project.placeholder.none": "No screenshots yet",
  "project.placeholder.planned": "In planning",
  "project.repo": "Source code",
  "project.stack": "Stack",
  "project.started": "Started",
  "project.status": "Status",
  "project.type.client": "Client",
  "project.type.learning": "Learning",
  "project.type.personal": "Personal",
  "project.typeLabel": "Type",
  "project.visit": "Visit site",
  "projects.filterLabel": "Filter by type",
  "projects.intro":
    "Client work, my own products and experiments, and the early work where it all started.",
  "projects.title": "From first idea to shipped product.",
  "projects.typeHint.client": "Built for clients.",
  "projects.typeHint.learning": "My early work, from when I was learning.",
  "projects.typeHint.personal": "My own products and experiments.",
  "record.duration": "Duration",
  "record.highlights": "Highlights",
  "record.overview": "Overview",
  "record.products": "Products",
  "record.projects": "Projects from this period",
  "record.scope": "Scope",
  "section.certifications": "Certifications",
  "section.education": "Education",
  "section.experience": "Experience",
  "section.projects": "Projects",
  "stack.group.architecture": "Architecture",
  "stack.group.backend": "Backend & data",
  "stack.group.frontend": "Frontend",
  "stack.group.tools": "Tools & process",
  "status.completed": "Completed",
  "status.in progress": "In progress",
  "status.planned": "Planned",
  "theme.toDark": "Switch to dark theme",
  "theme.toLight": "Switch to light theme",
  "timeline.chart.architecture": "Architecture",
  "timeline.chart.software": "Software",
  "timeline.chart.summary":
    "Chart of studies, roles, projects and certifications over time. The full record is listed below.",
  "timeline.chart.today": "Today",
  "timeline.chart.transition": "Transition",
  "timeline.clearFilters": "Clear filters",
  "timeline.currentHint": "My current job and projects in progress",
  "timeline.currentOnly": "Current only",
  "timeline.filterLabel": "Filter by category",
  "timeline.filters": "Filters",
  "timeline.filtersNoResults": "No results",
  "timeline.legend.certifications": "Certification",
  "timeline.legend.education": "Education",
  "timeline.legend.experience": "Work",
  "timeline.legend.projects": "Project",
  "timeline.newest": "Newest",
  "timeline.noResults": "Nothing matches these filters.",
  "timeline.oldest": "Oldest",
  "timeline.projectTypes": "Project type",
  "timeline.resultCount": "{n} results",
  "timeline.resultCount.one": "1 result",
  "timeline.searchLabel": "Search the timeline",
  "timeline.searchPlaceholder": "Search: React, client, 2024…",
  "timeline.showResult": "Show 1 result",
  "timeline.showResults": "Show {n} results",
  "timeline.sortNewest": "Show newest first",
  "timeline.sortOldest": "Show oldest first",
  "timeline.subtitle":
    "Studies, work, projects and certifications on one timeline, from my first degree to today.",
  "timeline.techStack": "Stack",
  "timeline.title": "The path so far.",
} as const;

export type UiKey = keyof typeof en;
