import type { UiKey } from "./en";

export const pt: Record<UiKey, string> = {
  "a11y.breadcrumb": "Navegação estrutural",
  "a11y.skip": "Saltar para o conteúdo",
  "about.bio":
    "Vivo em Lisboa e construo para a web desde 2023, sobretudo com React, Next.js e TypeScript.\n\nAntes disso fui arquiteto, e a minha tese de mestrado foi sobre arquitetura e videojogos. Os jogos ficaram comigo: vários dos meus projetos são companions de jogos, como o Voydex, um companion de Pokémon que estou a construir agora. Os outros são sobretudo pequenos trackers para coisas de que gosto, de concertos a finanças.",
  "about.facts.based": "Baseado em",
  "about.facts.current": "Atualmente",
  "about.facts.degree": "Formação",
  "about.facts.frontendSince": "Frontend desde",
  "about.intro": "Um frontend developer com formação em arquitetura e interesse por UX e UI.",
  "about.method.access.body":
    "Uso HTML semântico, suporte de teclado e bom contraste, e testo em vários tamanhos de ecrã.",
  "about.method.access.title": "Acessibilidade",
  "about.method.design.body":
    "Dou atenção à hierarquia, ao espaçamento e aos estados, para que os ecrãs sejam fáceis de ler.",
  "about.method.design.title": "Design",
  "about.method.intro": "Quatro princípios por trás de tudo o que construo.",
  "about.method.longevity.body":
    "Escrevo código tipado e legível e arrumo à medida que avanço, para que continue fácil de alterar.",
  "about.method.longevity.title": "Longevidade",
  "about.method.structure.body":
    "Planeio componentes e layouts antes de construir, para que seja mais fácil acrescentar funcionalidades.",
  "about.method.structure.title": "Estrutura",
  "about.method.title": "Como trabalho.",
  "about.story.practice.title": "Arquiteto",
  "about.story.school.title": "Faculdade de arquitetura",
  "about.story.software.body":
    "Funções full-stack na Subvisual e na Talent Protocol, depois frontend na Aquasis, com projetos pessoais e de clientes pelo caminho.",
  "about.story.software.title": "Frontend",
  "about.story.title": "Como cheguei ao frontend.",
  "about.story.transition.title": "A mudança",
  "about.title": "Olá, sou o Tiago.",
  "about.toolbox.title": "Com o que trabalho.",
  "common.all": "Todos",
  "common.backToTop": "Voltar ao topo",
  "common.entries": "entradas",
  "common.entry": "entrada",
  "common.fullTimeline": "Percurso completo",
  "common.next": "Seguinte",
  "common.portraitAlt": "Retrato de Tiago Gil ao ar livre, ao pôr do sol, a olhar para o lado.",
  "common.present": "Presente",
  "common.previous": "Anterior",
  "contact.body":
    "Estou disponível para projetos freelance: websites, aplicações web e interfaces. A forma mais rápida de me contactar é por email.",
  "contact.copied": "Copiado",
  "contact.copy": "Copiar email",
  "contact.cv": "Descarregar CV",
  "contact.title": "Vamos conversar.",
  "duration.month": "mês",
  "duration.months": "meses",
  "duration.year": "ano",
  "duration.years": "anos",
  "footer.contact": "Contacto",
  "footer.index": "Índice",
  "footer.note": "Frontend developer e ex-arquiteto, baseado em Lisboa.",
  "footer.updated": "Última atualização",
  "home.experience.title": "Onde trabalhei.",
  "home.hero.ctaWork": "Ver trabalho selecionado",
  "home.hero.lead":
    "Trabalho sobretudo com React, Next.js e TypeScript. A minha formação em arquitetura faz-me dar muita atenção à estrutura e ao design. Atualmente na Aquasis, em Lisboa, e disponível para freelance.",
  "home.hero.line1": "Frontend developer",
  "home.hero.line2": "& arquiteto.",
  "home.work.all": "Todos os projetos",
  "home.work.title": "Algumas coisas que desenhei e construí.",
  "language.label": "Idioma",
  "lightbox.counter": "{n} de {total}",
  "lightbox.label": "Imagens de {title}",
  "lightbox.next": "Imagem seguinte",
  "lightbox.previous": "Imagem anterior",
  "nav.about": "Sobre",
  "nav.close": "Fechar",
  "nav.contact": "Contacto",
  "nav.home": "Início",
  "nav.homeLabel": "Tiago Gil, início",
  "nav.label": "Principal",
  "nav.menu": "Menu",
  "nav.projects": "Projetos",
  "nav.timeline": "Percurso",
  "notFound.body": "Pode ter mudado de sítio, ou o endereço pode estar errado.",
  "notFound.home": "Voltar ao início",
  "notFound.label": "Não encontrado",
  "notFound.title": "Esta página não existe.",
  "project.brief": "Resumo",
  "project.collection": "Nesta coleção",
  "project.context": "Contexto",
  "project.enlarge": "Ampliar",
  "project.figures": "Figuras",
  "project.imageNumbered": "Captura {n} de {total} de {title}",
  "project.personal": "Projeto pessoal",
  "project.placeholder.none": "Ainda sem imagens",
  "project.placeholder.planned": "Em planeamento",
  "project.repo": "Código-fonte",
  "project.stack": "Tecnologias",
  "project.started": "Início",
  "project.status": "Estado",
  "project.type.client": "Cliente",
  "project.type.learning": "Aprendizagem",
  "project.type.personal": "Pessoal",
  "project.typeLabel": "Tipo",
  "project.visit": "Visitar site",
  "projects.filterLabel": "Filtrar por tipo",
  "projects.intro":
    "Trabalho para clientes, os meus produtos e experiências, e os primeiros trabalhos onde tudo começou.",
  "projects.title": "Da primeira ideia ao produto final.",
  "projects.typeHint.client": "Feitos para clientes.",
  "projects.typeHint.learning": "Os meus primeiros trabalhos, de quando estava a aprender.",
  "projects.typeHint.personal": "Os meus produtos e experiências.",
  "record.duration": "Duração",
  "record.highlights": "Destaques",
  "record.overview": "Visão geral",
  "record.products": "Produtos",
  "record.projects": "Projetos deste período",
  "record.scope": "Âmbito",
  "section.certifications": "Certificações",
  "section.education": "Formação",
  "section.experience": "Experiência",
  "section.projects": "Projetos",
  "stack.group.architecture": "Arquitetura",
  "stack.group.backend": "Backend e dados",
  "stack.group.frontend": "Frontend",
  "stack.group.tools": "Ferramentas e processo",
  "status.completed": "Concluído",
  "status.in progress": "Em curso",
  "status.planned": "Planeado",
  "theme.toDark": "Mudar para tema escuro",
  "theme.toLight": "Mudar para tema claro",
  "timeline.chart.architecture": "Arquitetura",
  "timeline.chart.software": "Software",
  "timeline.chart.summary":
    "Gráfico com estudos, funções, projetos e certificações ao longo do tempo. O registo completo está listado abaixo.",
  "timeline.chart.today": "Hoje",
  "timeline.chart.transition": "Transição",
  "timeline.clearFilters": "Limpar filtros",
  "timeline.currentHint": "O meu trabalho atual e projetos em curso",
  "timeline.currentOnly": "Apenas o atual",
  "timeline.filterLabel": "Filtrar por categoria",
  "timeline.filters": "Filtros",
  "timeline.filtersNoResults": "Sem resultados",
  "timeline.legend.certifications": "Certificação",
  "timeline.legend.education": "Formação",
  "timeline.legend.experience": "Trabalho",
  "timeline.legend.projects": "Projeto",
  "timeline.newest": "Recentes",
  "timeline.noResults": "Nada corresponde a estes filtros.",
  "timeline.oldest": "Antigos",
  "timeline.projectTypes": "Tipo de projeto",
  "timeline.resultCount": "{n} resultados",
  "timeline.resultCount.one": "1 resultado",
  "timeline.searchLabel": "Pesquisar no percurso",
  "timeline.searchPlaceholder": "Pesquisar: React, cliente, 2024…",
  "timeline.showResult": "Mostrar 1 resultado",
  "timeline.showResults": "Mostrar {n} resultados",
  "timeline.sortNewest": "Mostrar os mais recentes primeiro",
  "timeline.sortOldest": "Mostrar os mais antigos primeiro",
  "timeline.subtitle":
    "Estudos, trabalho, projetos e certificações numa só linha do tempo, da primeira formação até hoje.",
  "timeline.techStack": "Tecnologias",
  "timeline.title": "O percurso até aqui.",
};
