// Interface text in European Portuguese (pt-PT). Same keys as en.ts.
import type { UiKey } from "./en";

export const pt: Record<UiKey, string> = {
  "a11y.breadcrumb": "Navegação estrutural",
  "a11y.skip": "Saltar para o conteúdo",
  "about.bio":
    "Vivo em Lisboa e construo para a web desde 2023, sobretudo com React, Next.js e TypeScript.\n\nAntes disso fui arquiteto, e a minha tese de mestrado foi sobre arquitetura e videojogos. Os jogos ficaram comigo: vários dos meus projetos são companions de jogos, como o Voydex, um companion de Pokémon que estou a construir agora. Os outros são sobretudo pequenos trackers para coisas de que gosto, de concertos a finanças.",
  "about.facts.degree": "Formação",
  "about.facts.frontendSince": "Frontend desde",
  "about.intro":
    "Um frontend developer com formação em arquitetura e interesse por UX e UI.",
  "about.learning.title": "Formação e certificações.",
  "about.story.practice.title": "Arquiteto",
  "about.story.school.title": "Faculdade de arquitetura",
  "about.story.software.body":
    "Funções full-stack na Subvisual e na Talent Protocol, depois frontend na Aquasis, com projetos pessoais e de clientes pelo caminho.",
  "about.story.software.title": "Frontend",
  "about.story.title": "Como cheguei ao frontend.",
  "about.story.transition.title": "A mudança",
  "about.title": "Olá, sou o Tiago.",
  "about.toolbox.architecture": "Arquitetura",
  "about.toolbox.data": "Dados e back end",
  "about.toolbox.interface": "Interface",
  "about.toolbox.other": "Outros",
  "about.toolbox.process": "Processo",
  "about.toolbox.title": "Com o que trabalho.",
  "about.toolbox.web3": "Web3",
  "certification.visit": "Ver curso",
  "common.at": "na",
  "common.backToTop": "Voltar ao topo",
  "common.next": "Seguinte",
  "common.previous": "Anterior",
  "contact.body":
    "Estou disponível para projetos freelance: websites, aplicações web e interfaces. A forma mais rápida de me contactar é por email.",
  "contact.copied": "Copiado",
  "contact.copy": "Copiar email",
  "contact.cv": "Descarregar CV",
  "contact.emailLabel": "Email",
  "contact.title": "Vamos conversar.",
  "duration.month": "mês",
  "duration.months": "meses",
  "duration.year": "ano",
  "duration.years": "anos",
  "education.certificate": "Ver certificado",
  "education.thesis": "Ler a tese",
  "error.body":
    "Um erro inesperado impediu esta página de ser apresentada. Recarregar costuma resolver.",
  "error.code": "Erro",
  "error.home": "Voltar ao início",
  "error.title": "Algo falhou nesta folha.",
  "footer.contact": "Contacto",
  "footer.index": "Índice",
  "footer.madeBy": "Desenhado e construído por",
  "footer.note": "Frontend developer e ex-arquiteto, baseado em Lisboa.",
  "footer.updated": "Última atualização",
  "home.experience.timeline": "Percurso completo",
  "home.experience.title": "Onde trabalhei.",
  "home.hero.ctaWork": "Ver trabalho selecionado",
  "home.hero.facts.architectureSince": "Arquitetura desde",
  "home.hero.facts.based": "Baseado em",
  "home.hero.facts.current": "Atualmente",
  "home.hero.facts.location": "Lisboa, Portugal",
  "home.hero.facts.practice": "Prática",
  "home.hero.facts.softwareSince": "Software desde",
  "home.hero.lead":
    "Trabalho sobretudo com React, Next.js e TypeScript. A minha formação em arquitetura faz-me dar muita atenção à estrutura e ao design. Atualmente na Aquasis, em Lisboa, e disponível para freelance.",
  "home.hero.line1": "Frontend developer",
  "home.hero.line2": "& arquiteto.",
  "home.hero.portraitAlt":
    "Retrato de Tiago Gil ao ar livre, ao pôr do sol, a olhar para o lado.",
  "home.method.access.body":
    "Uso HTML semântico, suporte de teclado e bom contraste, e testo em vários tamanhos de ecrã.",
  "home.method.access.title": "Acessibilidade",
  "home.method.design.body":
    "Dou atenção à hierarquia, ao espaçamento e aos estados, para que os ecrãs sejam fáceis de ler.",
  "home.method.design.title": "Design",
  "home.method.detail.body":
    "Estados, espaçamento, movimento e acessibilidade com o mesmo cuidado que o conjunto. É no detalhe que um espaço se sente.",
  "home.method.detail.title": "O detalhe importa",
  "home.method.intro": "Quatro princípios por trás de tudo o que construo.",
  "home.method.longevity.body":
    "Escrevo código tipado e legível e arrumo à medida que avanço, para que continue fácil de alterar.",
  "home.method.longevity.title": "Longevidade",
  "home.method.structure.body":
    "Planeio componentes e layouts antes de construir, para que seja mais fácil acrescentar funcionalidades.",
  "home.method.structure.title": "Estrutura",
  "home.method.title": "Como trabalho.",
  "home.method.use.body":
    "Interfaces desenhadas à volta de quem as percorre: fluxos reais, clientes reais, testadas à mão.",
  "home.method.use.title": "Pensado para o uso",
  "home.work.all": "Todos os projetos",
  "home.work.title": "Algumas coisas que desenhei e construí.",
  "language.label": "Idioma",
  "nav.about": "Sobre",
  "nav.close": "Fechar",
  "nav.contact": "Contacto",
  "nav.home": "Início",
  "nav.homeLabel": "Tiago Gil, início",
  "nav.label": "Principal",
  "nav.menu": "Menu",
  "nav.projects": "Projetos",
  "nav.timeline": "Percurso",
  "notFound.body":
    "A página que procura não existe ou mudou de sítio. O início é um bom ponto de partida.",
  "notFound.home": "Voltar ao início",
  "notFound.label": "Não encontrado",
  "notFound.title": "Esta folha não faz parte do conjunto.",
  "project.brief": "Resumo",
  "project.collection": "Nesta coleção",
  "project.context": "Contexto",
  "project.enlarge": "Ampliar",
  "project.figures": "Figuras",
  "project.imageAlt": "Captura de ecrã de {title}",
  "project.more": "Mais projetos",
  "project.open": "Ver projeto",
  "project.personal": "Projeto pessoal",
  "project.placeholder.none": "Ainda sem imagens",
  "project.placeholder.planned": "Em planeamento",
  "project.repo": "Código-fonte",
  "project.scope": "Formato",
  "project.stack": "Tecnologias",
  "project.started": "Início",
  "project.status": "Estado",
  "project.type.client": "Cliente",
  "project.type.learning": "Aprendizagem",
  "project.type.personal": "Pessoal",
  "project.typeLabel": "Tipo",
  "project.visit": "Visitar site",
  "projects.filterLabel": "Filtrar por tipo",
  "projects.intro":
    "Trabalho para clientes, os meus produtos e experiências, e os primeiros trabalhos onde tudo começou.",
  "projects.title": "Da primeira ideia ao produto final.",
  "projects.typeHint.all": "Numerados pela ordem em que foram começados.",
  "projects.typeHint.client": "Feitos para clientes.",
  "projects.typeHint.learning":
    "Os meus primeiros trabalhos, de quando estava a aprender.",
  "projects.typeHint.personal": "Os meus produtos e experiências.",
  "record.duration": "Duração",
  "record.highlights": "Destaques",
  "record.more": "Mais do percurso",
  "record.overview": "Visão geral",
  "record.products": "Produtos",
  "record.projects": "Projetos deste período",
  "record.scope": "Âmbito",
  "section.certifications": "Certificações",
  "section.education": "Formação",
  "section.experience": "Experiência",
  "section.projects": "Projetos",
  "stack.group.architecture": "Arquitetura",
  "stack.group.backend": "Backend e dados",
  "stack.group.frontend": "Frontend",
  "stack.group.other": "Outros",
  "stack.group.tools": "Ferramentas e processo",
  "status.completed": "Concluído",
  "status.in progress": "Em curso",
  "status.planned": "Planeado",
  "theme.toDark": "Mudar para tema escuro",
  "theme.toLight": "Mudar para tema claro",
  "timeline.all": "Todos",
  "timeline.chart.architecture": "Arquitetura",
  "timeline.chart.entries": "entradas",
  "timeline.chart.software": "Software",
  "timeline.chart.summary":
    "Gráfico com estudos, funções, projetos e certificações ao longo do tempo. O registo completo está listado abaixo.",
  "timeline.chart.today": "Hoje",
  "timeline.chart.transition": "Transição",
  "timeline.clearAdvancedFilters": "Limpar filtros",
  "timeline.currentHint": "O meu trabalho atual e projetos em curso",
  "timeline.currentOnly": "Apenas o atual",
  "timeline.entries": "entradas",
  "timeline.entry": "entrada",
  "timeline.filterLabel": "Filtrar por categoria",
  "timeline.filters": "Filtros",
  "timeline.filtersNoResults": "Sem resultados",
  "timeline.legend": "Legenda",
  "timeline.legend.certifications": "Certificação",
  "timeline.legend.education": "Formação",
  "timeline.legend.experience": "Trabalho",
  "timeline.legend.projects": "Projeto",
  "timeline.newest": "Recentes",
  "timeline.noResults": "Nada corresponde a estes filtros.",
  "timeline.oldest": "Antigos",
  "timeline.present": "Presente",
  "timeline.projectTypes": "Tipo de projeto",
  "timeline.recordLabel": "Registo completo",
  "timeline.searchLabel": "Pesquisar no percurso",
  "timeline.searchPlaceholder": "Pesquisar: React, cliente, 2024…",
  "timeline.showResult": "Mostrar 1 resultado",
  "timeline.showResults": "Mostrar {n} resultados",
  "timeline.sortNewest": "Mostrar os mais recentes primeiro",
  "timeline.sortOldest": "Mostrar os mais antigos primeiro",
  "timeline.subtitle":
    "Estudos, trabalho, projetos e certificações numa só linha do tempo, da primeira formação até hoje.",
  "timeline.techStack": "Tecnologias",
  "timeline.title": "O percurso até aqui.",
};
